### PR TITLE
- fixed the typescript erros for better reliablity

### LINKED ISSUE #43: Better type safety where required
Currently, all the components are working fine, but some (2-3) components have loose type safety, which can be improved.
The components are related to the Path Screen

### PR DESCRIPTION
**Pull request by simarjot0032**
# Changes made
### PathScreen 
- Updated the typesafety for the fadeAnim
### PathReader component
- Removed the logic for font size in path reader components as it was already there in the simplepathtext component.
### SimpleTextForPath component
- Updated the typescript modification for some state as previouse it was using the React Dispatch which was not needed now I have update them to the simpler way
### PathControl component
- Update the fadeAnim to fadeAnim.current for better type safety

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@simarjot0032 veerji, can you please add some description, a little detailed note on changelog to help me understand this change.

**Comment by simarjot0032** [comment]
@Gauravjeetsingh  veerji I have added the description to the PR

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Good work, no specific comments, but I did found few typescript errors, which can be fixed as part of this PR

Image

**Comment by simarjot0032** [comment]
@Gauravjeetsingh  veer ji I have fixed the tsc --noEmit issues also

File: hooks/useNavigation.ts [hunk 1]
```diff
@@ -56,7 +56,9 @@ export const useNavigation = ({
       try {
         await fetchFromBaniDB(pageNo + 1);
         setAngNavigationNumber(pageNo + 1);
-        setPathPunjabiAng(convertNumberToFormat(pageNo + 1, angsFormat.format));
+        setPathPunjabiAng(
+          convertNumberToFormat(pageNo + 1, angsFormat.format as 'Punjabi' | 'English')
```
Comment (Gauravjeetsingh) [inline hooks/useNavigation.ts]: @simarjot0032 Type assertion is generally not a good way to validate. 

- Using `as` tells TypeScript to ignore type checking
- It could cause errors if unexpected values are passed.

Define the correct type, instead of setting format to `string`, define its type as `'Punjabi' | 'English'`
```javascript
export interface AngsFormat {
  format: 'Punjabi' | 'English';
}
```

There are few more places where I have seen `as` Can you look into that and use proper type checking, instead of asserting it.

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]

**Comment by simarjot0032** [comment]
@Gauravjeetsingh  veerji I have fixed the all type assertion.

**Review by Gauravjeetsingh — APPROVED** [review]
