### PR TITLE
Fix typo

### LINKED ISSUE #66: Fix typos in the app
- The app have some typo which need to fixed
- It’s “a” fine day to start a Sehaj Path should be changed to “It’s a fine day for a Sehaj Path” (because users will not be starting a new path every time)
- under progress “started” is spelled wrong
- We should change Ang under settings to “Ang Numbering”
- Last pantkee founded should be “Resuming saved  progress”

### PR DESCRIPTION
**Pull request by simarjot0032**
- Fixed the TYPOS according to the feedback
- Changes:
     -  It’s “a” fine day to start a Sehaj Path -> “It’s a fine day for a Sehaj Path” 
     - “started” was spelled wrong
     -  Ang under settings to “Ang Numbering”
     - Last pantkee founded should be “Resuming saved  progress”

### CODE REVIEW

File: constants/constant.ts [hunk 1]
```diff
@@ -6,8 +6,8 @@ export const Constants: Constant = {
   BUILDING_THE_HABIT: 'Building the habit',
   OF_READING_GURBANI: 'of reading Gurbani.',
   SEHAJ: 'Sehaj',
-  ITS_FINE_DAY_TO_START_A: "It's Fine day to start a",
-  NEW_SEHAJ_PATH: 'new Sehaj Path',
+  ITS_FINE_DAY_TO_START_A: "It's a Fine day for",
```
Comment (Gauravjeetsingh) [inline constants/constant.ts:9]: Shouldn't it be: 
`It's a fine day for`

Small `f` in `fine`.

**Review by Gauravjeetsingh — APPROVED** [review]
Minor change, can merge after fixing that.

File: constants/constant.ts (hunk 1 above)
Comment (simarjot0032) [reply constants/constant.ts:9]: veer ji as currently we are using the free version of the font that is why F is not available in that I will talk to inder veer ji regarding this
