### PR TITLE
- streak calculation fix

### LINKED ISSUE #53: Streak Calculation is not working properly
- The calendar streak is showing the max streak instead of the current streak

### PR DESCRIPTION
**Pull request by simarjot0032**
- Now it is calculating the current streak 
- Initally it was calcuting the max streak instead of the current streak

### CODE REVIEW

File: components/Calender.tsx [hunk 1]
```diff
@@ -25,23 +25,21 @@ export const Calender = ({ pathId, streak, onStreakUpdate }: Props) => {
 
     const sortedDates = dates
       .map((dateStr) => dayjs(dateStr, 'D-MMMM-YYYY'))
-      .sort((a, b) => a.diff(b, 'day'));
+      .sort((a, b) => b.diff(a, 'day'));
```
Comment (Gauravjeetsingh) [inline components/Calender.tsx]: Can we use better variable names, something that describe what a and b are here.

File: components/Calender.tsx [hunk 2]
```diff
@@ -25,23 +25,21 @@ export const Calender = ({ pathId, streak, onStreakUpdate }: Props) => {
...
 
     let currentStreak = 1;
-    let maxStreak = 1;
 
-    for (let i = 1; i < sortedDates.length; i++) {
-      const prevDate = sortedDates[i - 1];
+    for (let i = 0; i < sortedDates.length - 1; i++) {
```
Comment (Gauravjeetsingh) [inline components/Calender.tsx:32]: Can we use in loop here?

```javascript
for (let index in sortedDates) {

}
```

**Review by Gauravjeetsingh — APPROVED** [review]
Minor changes, you can merge after doing those.

File: components/Calender.tsx (hunk 2 above)
Comment (simarjot0032) [reply components/Calender.tsx:32]: yes veer ji I tried for in and the for of but the performace with the for loop is slightly better

Comment (Gauravjeetsingh) [reply components/Calender.tsx:32]: Alright!
