### PR TITLE
- ios long press fix

### LINKED ISSUE #80: Long press not working on IOS
- The long press for saving path is not working on IOS

### PR DESCRIPTION
**Pull request by simarjot0032**
Problem- The long press was not working on iOS
- This PR addresses iOS-specific long-press gesture issues and significantly improves the performance of the PathScreen component through comprehensive optimisations and refactoring.
- Refactored component structure for better performance
- Optimised state management and effect dependencies

### CODE REVIEW

File: components/SimpleTextForPath.tsx [hunk 1]
```diff
@@ -62,35 +61,52 @@ export const SimpleTextForPath = ({
...
-        setIsLongPressing(true);
         setIsSaving(true);
         setIsSaved(true);
         setPressIndex(index);
         setSavedPathVerseId(verseId);
         onSave();
-        setIsLongPressing(false);
-        animationRef.current = null;
+        setTimeout(() => {
+          isLongPressingRef.current = false;
```
Comment (Gauravjeetsingh) [inline components/SimpleTextForPath.tsx]: Wouldn't this cause a race condition if user long-presses again quickly?

File: components/PathNavigation.tsx [hunk 2]
```diff
@@ -13,25 +13,36 @@ interface PathNavigationProps {
   setIsAngsNavigationVisible: (isVisible: boolean) => void;
 }
 
-export const PathNavigation = ({
+const PathNavigationComponent = ({
```
Comment (Gauravjeetsingh) [inline components/PathNavigation.tsx:16]: Missing prop validation for this.

**Review by Gauravjeetsingh — COMMENTED** [review]
Minor changes for this one. Added comments. 

Also, the PR needs a better description, what bug does it solve, how does it improve performance. It will help me with reviews if the descriptions give brief information about the bug and how this solves it.

File: components/PathNavigation.tsx (hunk 2 above)
Comment (simarjot0032) [reply components/PathNavigation.tsx:16]: Veer ji we already have the interfrace do we also need extra validation?

**Review by Gauravjeetsingh — APPROVED** [review]
