### PR TITLE
Ios scroll fade

### LINKED ISSUE #47: Fade animation not working in IOS
- the animation which appers on message appers on the bottom of the path screen is not working

### LINKED ISSUE #48: Auto scroll not working in IOS

### PR DESCRIPTION
**Pull request by simarjot0032**
- Fixed the Internet checking method for better perfomance for ios
- Changed the approach from the setTimeout and setInterval to Animated.timing 
- Fixed the scroll and animation in IOS

### CODE REVIEW

File: components/AngsNavigation.tsx [hunk 1]
```diff
@@ -52,43 +52,45 @@ export const AngsNavigation = ({
...
-      setIsAngsNavigationVisible(false);
-    } catch (error) {
-      showErrorAlert(ErrorConstants.FAILED_TO_CHECK_NETWORK_CONNECTION);
-    }
+  const handleNavigation = (navigationFunction: () => void) => {
+    checkNetwork()
+      .then((isConnected) => {
+        if (!isConnected) {
+          showErrorAlert(
+            ErrorConstants.NO_INTERNET_TITLE + '\n' + ErrorConstants.NO_INTERNET_MESSAGE
```
Comment (Gauravjeetsingh) [inline components/AngsNavigation.tsx]: We can use template string here.

```javascript
`${ErrorConstants.NO_INTERNET_TITLE}\n ${ErrorConstants.NO_INTERNET_MESSAGE}`
```

File: components/SimpleTextForPath.tsx [hunk 2]
```diff
@@ -68,22 +60,21 @@ export const SimpleTextForPath = ({
...
-    timeoutRef.current = setTimeout(() => {
+    Animated.timing(new Animated.Value(0), {
+      toValue: 1,
+      duration: 100,
+      useNativeDriver: true,
+    }).start(() => {
+      onSelection();
+      setIsLongPressing(true);
+      setIsSaving(true);
+      setIsSaved(true);
```
Comment (Gauravjeetsingh) [inline components/SimpleTextForPath.tsx:73]: What is difference between states setIsSaving and setIsSaved?

Is there any use case, where these two would have different value?

In this case, both are set to true at same time.

File: hooks/useInternet.ts [hunk 3]
```diff
@@ -4,27 +4,53 @@ import { useState, useEffect } from 'react';
...
+      NetInfo.fetch()
+        .then((netInfo) => {
+          clearTimeout(timeout);
+          const isConnected = Boolean(netInfo.isConnected);
+          setIsOnline(isConnected);
+          resolve(isConnected);
+        })
+        .catch((error) => {
+          clearTimeout(timeout);
+          console.error('Error in checkNetwork:', error);
```
Comment (Gauravjeetsingh) [inline hooks/useInternet.ts]: We can remove this console message

File: hooks/useLocal.ts [hunk 4]
```diff
@@ -138,14 +138,18 @@ export const useLocal = () => {
...
+        await Promise.all([
+          AsyncStorage.setItem('pathDetails', JSON.stringify(pathDataArray)),
+          AsyncStorage.setItem('pathDateDetails', JSON.stringify(updatedPathDate)),
+        ]);
 
-        await AsyncStorage.setItem('pathDetails', JSON.stringify(pathDataArray));
-        await AsyncStorage.setItem('pathDateDetails', JSON.stringify(updatedPathDate));
         setIsSaved(true);
       } else {
+        console.error('Failed to find matched path or date');
```
Comment (Gauravjeetsingh) [inline hooks/useLocal.ts]: Any reason on why we need the console messages here?

File: hooks/useInternet.ts (hunk 3 above)
Comment (Gauravjeetsingh) [reply hooks/useInternet.ts]: There are bunch of other console messages in the code, can you take care of those too, if they aren't added for any specific reason.

File: hooks/useNavigation.ts [hunk 5]
```diff
@@ -30,31 +31,35 @@ export const useNavigation = ({
...
       scorllOffset.current = 0;
       scrollRef.current?.scrollTo({
         y: 0,
         animated: true,
       });
 
       try {
+        const isConnected = await checkNetwork();
+        if (!isConnected) {
+          console.log('showErrorAlert');
```
Comment (Gauravjeetsingh) [inline hooks/useNavigation.ts]: Another console message that can be removed.

File: hooks/useScrollToSavedPath.ts [hunk 6]
```diff
@@ -31,36 +30,36 @@ export const useScrollToSavedPath = ({
...
+    Animated.sequence([
+      Animated.delay(2500),
+      Animated.timing(fadeAnim, {
+        toValue: 0,
+        duration: 2500,
+        useNativeDriver: true,
+      }),
+    ]).start(() => {
+      setIsSaving(false);
+      setIsSaved(false);
```
Comment (Gauravjeetsingh) [inline hooks/useScrollToSavedPath.ts:46]: Another place, where both setIsSaving and setIsSaved are assigned same value at same place.

File: screens/PathScreen.tsx [hunk 7]
```diff
@@ -47,26 +48,40 @@ export const PathScreen = ({ navigation, route }: PathScreenProps) => {
...
   const [angNavigationNumber, setAngNavigationNumber] = useState<number>(0);
   const [isNavigating, setIsNavigating] = useState<boolean>(false);
-  const scrolledToSavedPath = useRef(false);
-  const scrollInveral = useRef<NodeJS.Timeout | null>(null);
+  const [needsRetry, setNeedsRetry] = useState<boolean>(false);
+  const [lastFailedAng, setLastFailedAng] = useState<number | null>(null);
+  const scrolledToSavedPath = useRef<boolean>(false);
   const scorllOffset = useRef<number>(0);
   const scrollRef = useRef<ScrollView | null>(null);
   const aleartIndicator = useRef<React.ReactNode>();
```
Comment (Gauravjeetsingh) [inline screens/PathScreen.tsx]: Misspelled alert in above variable.

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Added few comments, have a look

File: components/SimpleTextForPath.tsx (hunk 2 above)
Comment (simarjot0032) [reply components/SimpleTextForPath.tsx:73]: Yes veerji we have 2 states for saving panktee
1- for when user click on save button which show msg 'Select a panktee to save'
2- when user select which shows msg 'Select panktee saved'
but when user tries to saves using the long press we dont show the 'Select a panktee to save'

File: hooks/useScrollToSavedPath.ts (hunk 6 above)
Comment (simarjot0032) [reply hooks/useScrollToSavedPath.ts:46]: yes veer ji this is when the path is loaded it shows the Last saved panktee found for that other are being false

File: components/SimpleTextForPath.tsx (hunk 2 above)
Comment (Gauravjeetsingh) [reply components/SimpleTextForPath.tsx:73]: Got it

**Review by Gauravjeetsingh — APPROVED** [review]
